# Generated by Django 5.2.17 on 2026-08-16 22:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(editable=False, unique=True)),
                ('organization_name', models.CharField(blank=True, default='', max_length=255)),
                ('organization_type', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20)),
                ('provider', models.CharField(default='stripe', max_length=32)),
                ('provider_customer_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['organization_name', 'organization_id'],
                'indexes': [models.Index(fields=['status'], name='billing_bil_status_a9d807_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('provider_customer_id', ''), _negated=True), fields=('provider', 'provider_customer_id'), name='billing_provider_customer_unique')],
            },
        ),
        migrations.CreateModel(
            name='MemberOrganizationLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parent_organization_id', models.UUIDField(db_index=True)),
                ('child_organization_id', models.UUIDField(db_index=True)),
                ('source', models.CharField(default='legacy_migration', max_length=64)),
                ('observed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['parent_organization_id', 'child_organization_id'],
                'constraints': [models.UniqueConstraint(fields=('parent_organization_id', 'child_organization_id'), name='billing_member_link_unique'), models.CheckConstraint(condition=models.Q(('parent_organization_id', models.F('child_organization_id')), _negated=True), name='billing_member_link_no_self')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('unpaid', 'Unpaid'), ('paused', 'Paused'), ('canceled', 'Cancelled'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete (expired)'), ('unknown', 'Unknown')], default='incomplete', max_length=32)),
                ('provider', models.CharField(default='stripe', max_length=32)),
                ('provider_subscription_id', models.CharField(max_length=255)),
                ('provider_customer_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('provider_sequence', models.BigIntegerField(default=0)),
                ('provider_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.billingaccount')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='catalog.plan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='stripe', max_length=32)),
                ('provider_invoice_id', models.CharField(max_length=255)),
                ('number', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('paid', 'Paid'), ('uncollectible', 'Uncollectible'), ('void', 'Void'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('total_minor', models.IntegerField(default=0)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('hosted_url', models.URLField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='billing.billingaccount')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.subscription')),
            ],
            options={
                'ordering': ['-issued_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_item_id', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_items', to='catalog.planprice')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.subscription')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identity_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('display_name', models.CharField(blank=True, default='', max_length=200)),
                ('role', models.CharField(choices=[('primary', 'Primary billing contact'), ('finance', 'Finance')], default='primary', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='billing.billingaccount')),
            ],
            options={
                'ordering': ['role', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('account', 'role'), name='billing_contact_account_role_unique'), models.CheckConstraint(condition=models.Q(('identity_user_id__isnull', False), models.Q(('email', ''), _negated=True), _connector='OR'), name='billing_contact_identifiable')],
            },
        ),
        migrations.CreateModel(
            name='ComplimentaryGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField()),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('granted_by_user_id', models.UUIDField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_by_user_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='billing.billingaccount')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='catalog.plan')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account', 'revoked_at', 'expires_at'], name='billing_com_account_9e5472_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['account', 'state'], name='billing_sub_account_79ede0_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['state', 'current_period_end'], name='billing_sub_state_b72d61_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_subscription_id'), name='billing_provider_subscription_unique'),
        ),
        migrations.AddConstraint(
            model_name='invoicereference',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_invoice_id'), name='billing_provider_invoice_unique'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionitem',
            constraint=models.UniqueConstraint(fields=('subscription', 'price'), name='billing_subscription_price_unique'),
        ),
    ]
