# Generated by Django 5.2.17 on 2026-08-17 00:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntitlementAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('beneficiary_organization_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ineligible', 'Ineligible'), ('released', 'Released')], default='active', max_length=20)),
                ('status_reason', models.CharField(blank=True, default='', max_length=255)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('created_under_graph_version', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='billing.subscription')),
            ],
            options={
                'ordering': ['beneficiary_organization_id', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationalAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('sponsorship_lapsed', 'Sponsorship relationship removed'), ('graph_stale', 'Organisation graph is stale'), ('beneficiary_unknown', 'Beneficiary organisation not in graph')], db_index=True, max_length=40)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('beneficiary_organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by_user_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='billing.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='MemberOrganizationLink',
        ),
        migrations.AddIndex(
            model_name='entitlementallocation',
            index=models.Index(fields=['beneficiary_organization_id', 'status'], name='billing_ent_benefic_9404d6_idx'),
        ),
        migrations.AddConstraint(
            model_name='entitlementallocation',
            constraint=models.UniqueConstraint(fields=('subscription', 'beneficiary_organization_id'), name='billing_allocation_unique'),
        ),
        migrations.AddIndex(
            model_name='operationalalert',
            index=models.Index(fields=['kind', 'acknowledged_at'], name='billing_ope_kind_0a54ca_idx'),
        ),
    ]
