# Generated by Django 5.2.17 on 2026-08-16 22:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_system', models.CharField(max_length=64)),
                ('operation', models.CharField(choices=[('dry_run', 'Dry run'), ('apply', 'Apply'), ('reconcile', 'Reconcile')], max_length=16)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('conflict', 'Conflict'), ('failed', 'Failed')], max_length=16)),
                ('export_schema_version', models.PositiveSmallIntegerField()),
                ('exporter_version', models.CharField(max_length=32)),
                ('artifact_sha256', models.CharField(db_index=True, max_length=64)),
                ('manifest_checksum', models.CharField(max_length=64)),
                ('source_counts', models.JSONField(default=dict)),
                ('result_counts', models.JSONField(default=dict)),
                ('conflict_counts', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['artifact_sha256', 'operation', 'status'], name='legacy_migr_artifac_efd651_idx')],
            },
        ),
        migrations.CreateModel(
            name='LegacyAccountMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_system', models.CharField(max_length=64)),
                ('source_kind', models.CharField(choices=[('practice', 'Practice'), ('pcn', 'PCN')], max_length=16)),
                ('source_record_id', models.CharField(max_length=64)),
                ('first_imported_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField()),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('target_fingerprint', models.CharField(max_length=64)),
                ('source_missing', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legacy_mappings', to='billing.billingaccount')),
                ('last_import_run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_mappings', to='legacy_migration.importrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source_system', 'source_kind', 'source_record_id'), name='legacy_account_source_unique'), models.UniqueConstraint(fields=('source_system', 'account'), name='legacy_account_target_unique')],
            },
        ),
        migrations.CreateModel(
            name='LegacyGrantMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_system', models.CharField(max_length=64)),
                ('source_record_id', models.CharField(max_length=64)),
                ('first_imported_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField()),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('target_fingerprint', models.CharField(max_length=64)),
                ('source_missing', models.BooleanField(default=False)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legacy_mappings', to='billing.complimentarygrant')),
                ('last_import_run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grant_mappings', to='legacy_migration.importrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source_system', 'source_record_id'), name='legacy_grant_source_unique'), models.UniqueConstraint(fields=('source_system', 'grant'), name='legacy_grant_target_unique')],
            },
        ),
        migrations.CreateModel(
            name='LegacySubscriptionMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_system', models.CharField(max_length=64)),
                ('source_record_id', models.CharField(max_length=64)),
                ('provider_reference_digest', models.CharField(db_index=True, max_length=64)),
                ('first_imported_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField()),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('target_fingerprint', models.CharField(max_length=64)),
                ('source_missing', models.BooleanField(default=False)),
                ('last_import_run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_mappings', to='legacy_migration.importrun')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legacy_mappings', to='billing.subscription')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source_system', 'source_record_id'), name='legacy_subscription_source_unique'), models.UniqueConstraint(fields=('source_system', 'subscription'), name='legacy_subscription_target_unique')],
            },
        ),
    ]
