# Generated by Django 5.2.17 on 2026-08-16 22:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='stripe', max_length=32)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('drifted', 'Drifted'), ('failed', 'Failed')], max_length=20)),
                ('counts', models.JSONField(default=dict)),
                ('applied', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='stripe', max_length=32)),
                ('provider_event_id', models.CharField(max_length=255)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('provider_created_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('applied', 'Applied'), ('duplicate', 'Duplicate'), ('out_of_order', 'Out of order'), ('ignored', 'Ignored'), ('unresolved', 'Unresolved'), ('failed', 'Failed')], db_index=True, max_length=20)),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('payload_digest', models.CharField(blank=True, default='', max_length=64)),
                ('delivery_count', models.PositiveIntegerField(default=1)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='billing.subscription')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['outcome', '-received_at'], name='providers_w_outcome_ab8ef2_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_event_id'), name='providers_event_unique')],
            },
        ),
    ]
