# Generated by Django 5.2.17 on 2026-08-17 00:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identityuser',
            name='is_platform_admin',
        ),
        migrations.CreateModel(
            name='OrganizationGraph',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('graph_version', models.CharField(max_length=64, unique=True)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('source', models.CharField(choices=[('identity_api', 'Haresign Identity API'), ('legacy_migration', 'Legacy migration import')], db_index=True, default='identity_api', max_length=32)),
                ('generated_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_current', models.BooleanField(db_index=True, default=False)),
                ('organization_count', models.PositiveIntegerField(default=0)),
                ('relationship_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-generated_at', '-fetched_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='identity_graph_single_current')],
            },
        ),
        migrations.CreateModel(
            name='GraphRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parent_organization_id', models.UUIDField(db_index=True)),
                ('child_organization_id', models.UUIDField(db_index=True)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='identity.organizationgraph')),
            ],
            options={
                'ordering': ['parent_organization_id', 'child_organization_id'],
                'constraints': [models.UniqueConstraint(fields=('graph', 'parent_organization_id', 'child_organization_id'), name='identity_graph_edge_unique'), models.CheckConstraint(condition=models.Q(('parent_organization_id', models.F('child_organization_id')), _negated=True), name='identity_graph_edge_no_self')],
            },
        ),
        migrations.CreateModel(
            name='GraphOrganization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('organization_type', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='identity.organizationgraph')),
            ],
            options={
                'ordering': ['organization_id'],
                'constraints': [models.UniqueConstraint(fields=('graph', 'organization_id'), name='identity_graph_org_unique')],
            },
        ),
    ]
