# Generated by Django 5.2.17 on 2026-08-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_remove_identityuser_is_platform_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationDisplayName',
            fields=[
                ('organization_id', models.UUIDField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=255)),
                ('organization_type', models.CharField(blank=True, default='', max_length=32)),
                ('fetched_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
    ]
