# Generated by Django 5.2.17 on 2026-08-16 22:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('support_access', models.BooleanField(db_index=True, default=False)),
                ('provider_event_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=400)),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'audit event',
                'verbose_name_plural': 'audit events',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['event', '-created_at'], name='audit_audit_event_56a1f3_idx'), models.Index(fields=['organization_id', '-created_at'], name='audit_audit_organiz_dbfe04_idx'), models.Index(fields=['support_access', '-created_at'], name='audit_audit_support_318ebc_idx')],
            },
        ),
    ]
