# Generated by Django 5.2.17 on 2026-08-16 22:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9_]{1,62}$', 'Keys are lowercase ASCII, start with a letter, and use only letters, digits and underscores.')])),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9_]{1,62}$', 'Keys are lowercase ASCII, start with a letter, and use only letters, digits and underscores.')])),
                ('name', models.CharField(max_length=200)),
                ('scope', models.CharField(choices=[('practice', 'GP practice'), ('pcn', 'Primary Care Network'), ('client', 'Consulting client'), ('internal', 'Internal')], db_index=True, max_length=20)),
                ('best_for', models.CharField(blank=True, default='', max_length=255)),
                ('covers_member_organizations', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(blank=True, related_name='plans', to='catalog.product')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='PlanPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interval', models.CharField(choices=[('month', 'Monthly'), ('year', 'Annual')], max_length=16)),
                ('amount_minor', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('provider', models.CharField(db_index=True, default='stripe', max_length=32)),
                ('provider_price_id', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='catalog.plan')),
            ],
            options={
                'ordering': ['plan__key', 'interval'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'interval', 'provider'), name='catalog_plan_interval_provider_unique'), models.UniqueConstraint(condition=models.Q(('provider_price_id', ''), _negated=True), fields=('provider', 'provider_price_id'), name='catalog_provider_price_unique')],
            },
        ),
    ]
